name: canvasthink
region: nyc
domains:
- domain: canvasthink.com
  type: PRIMARY
static_sites:
- build_command: npm run build
  environment_slug: node-js
  git:
    branch: master
    repo_clone_url: https://github.com/Huntman1210/canvasthink.git
  name: canvasthink-static
  output_dir: /dist
  index_document: index.html
  error_document: index.html
  catchall_document: index.html
  routes:
  - path: /
